# Generated by Django 5.2.3 on 2025-07-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conta',
            options={'ordering': ['-data_vencimento']},
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-data_pagamento']},
        ),
        migrations.RemoveField(
            model_name='conta',
            name='status',
        ),
        migrations.AlterUniqueTogether(
            name='pagamento',
            unique_together={('pessoa', 'conta')},
        ),
        migrations.AddField(
            model_name='conta',
            name='paga',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conta',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='forma_pagamento',
        ),
    ]
